module.exports = [
  {
    name: "கடவுள் வாழ்த்து",
    translation: "The Praise of God",
    transliteration: "Katavul Vaazhththu",
    id: 1,
    start: 1,
    end: 10,
    paalId: 1,
    iyalId: 1,
  },
  {
    name: "வான்சிறப்பு",
    translation: "The Blessing of Rain",
    transliteration: "Vaansirappu",
    id: 2,
    start: 11,
    end: 20,
    paalId: 1,
    iyalId: 1,
  },
  {
    name: "நீத்தார் பெருமை",
    translation: "The Greatness of Ascetics",
    transliteration: "Neeththaar Perumai",
    id: 3,
    start: 21,
    end: 30,
    paalId: 1,
    iyalId: 1,
  },
  {
    name: "அறன் வலியுறுத்தல்",
    translation: "Assertion of the Strength of Virtue",
    transliteration: "Aran Valiyuruththal",
    id: 4,
    start: 31,
    end: 40,
    paalId: 1,
    iyalId: 1,
  },
  {
    name: "இல்வாழ்க்கை",
    translation: "Domestic Life",
    transliteration: "Ilvaazhkkai",
    id: 5,
    start: 41,
    end: 50,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "வாழ்க்கைத் துணைநலம்",
    translation: "The Worth of a Wife",
    transliteration: "Vaazhkkaith Thunainalam",
    id: 6,
    start: 51,
    end: 60,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "மக்கட்பேறு",
    translation: "The Wealth of Children",
    transliteration: "Pudhalvaraip Perudhal",
    id: 7,
    start: 61,
    end: 70,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "அன்புடைமை",
    translation: "The Possession of Love",
    transliteration: "Anputaimai",
    id: 8,
    start: 71,
    end: 80,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "விருந்தோம்பல்",
    translation: "Hospitality",
    transliteration: "Virundhompal",
    id: 9,
    start: 81,
    end: 90,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "இனியவை கூறல்",
    translation: "The Utterance of Pleasant Words",
    transliteration: "Iniyavaikooral",
    id: 10,
    start: 91,
    end: 100,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "செய்ந்நன்றியறிதல்",
    translation: "Gratitude",
    transliteration: "Seynnandri Aridhal",
    id: 11,
    start: 101,
    end: 110,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "நடுவு நிலைமை",
    translation: "Impartiality",
    transliteration: "Natuvu Nilaimai",
    id: 12,
    start: 111,
    end: 120,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "அடக்கம் உடைமை",
    translation: "The Possession of Self-restraint",
    transliteration: "Atakkamutaimai",
    id: 13,
    start: 121,
    end: 130,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "ஒழுக்கம் உடைமை",
    translation: "The Possession of Decorum",
    transliteration: "Ozhukkamutaimai",
    id: 14,
    start: 131,
    end: 140,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "பிறனில் விழையாமை",
    translation: 'Not coveting another"s Wife',
    transliteration: "Piranil Vizhaiyaamai",
    id: 15,
    start: 141,
    end: 150,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "பொறையுடைமை",
    translation: "The Possession of Patience, Forbearance",
    transliteration: "Poraiyutaimai",
    id: 16,
    start: 151,
    end: 160,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "அழுக்காறாமை",
    translation: "Not Envying",
    transliteration: "Azhukkaaraamai",
    id: 17,
    start: 161,
    end: 170,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "வெஃகாமை",
    translation: "Not Coveting",
    transliteration: "Veqkaamai",
    id: 18,
    start: 171,
    end: 180,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "புறங்கூறாமை",
    translation: "Not Backbiting",
    transliteration: "Purangooraamai",
    id: 19,
    start: 181,
    end: 190,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "பயனில சொல்லாமை",
    translation: "Against Vain Speaking",
    transliteration: "Payanila Sollaamai",
    id: 20,
    start: 191,
    end: 200,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "தீவினையச்சம்",
    translation: "Dread of Evil Deeds",
    transliteration: "Theevinaiyachcham",
    id: 21,
    start: 201,
    end: 210,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "ஒப்புரவறிதல்",
    translation: "Duty to Society",
    transliteration: "Oppuravaridhal",
    id: 22,
    start: 211,
    end: 220,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "ஈகை",
    translation: "Giving",
    transliteration: "Eekai",
    id: 23,
    start: 221,
    end: 230,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "புகழ்",
    translation: "Renown",
    transliteration: "Pukazh",
    id: 24,
    start: 231,
    end: 240,
    paalId: 1,
    iyalId: 2,
  },
  {
    name: "அருளுடைமை",
    translation: "Compassion",
    transliteration: "Arulutaimai",
    id: 25,
    start: 241,
    end: 250,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "புலால் மறுத்தல்",
    translation: "Abstinence from Flesh",
    transliteration: "Pulaanmaruththal",
    id: 26,
    start: 251,
    end: 260,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "தவம்",
    translation: "Penance",
    transliteration: "Thavam",
    id: 27,
    start: 261,
    end: 270,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "கூடா ஒழுக்கம்",
    translation: "Imposture",
    transliteration: "Kootaavozhukkam",
    id: 28,
    start: 271,
    end: 280,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "கள்ளாமை",
    translation: "The Absence of Fraud",
    transliteration: "Kallaamai",
    id: 29,
    start: 281,
    end: 290,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "வாய்மை",
    translation: "Veracity",
    transliteration: "Vaaimai",
    id: 30,
    start: 291,
    end: 300,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "வெகுளாமை",
    translation: "Restraining Anger",
    transliteration: "Vekulaamai",
    id: 31,
    start: 301,
    end: 310,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "இன்னா செய்யாமை",
    translation: "Not doing Evil",
    transliteration: "Innaaseyyaamai",
    id: 32,
    start: 311,
    end: 320,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "கொல்லாமை",
    translation: "Not killing",
    transliteration: "Kollaamai",
    id: 33,
    start: 321,
    end: 330,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "நிலையாமை",
    translation: "Instability",
    transliteration: "Nilaiyaamai",
    id: 34,
    start: 331,
    end: 340,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "துறவு",
    translation: "Renunciation",
    transliteration: "Thuravu",
    id: 35,
    start: 341,
    end: 350,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "மெய்யுணர்தல்",
    translation: "Truth-Conciousness",
    transliteration: "Meyyunardhal",
    id: 36,
    start: 351,
    end: 360,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "அவா அறுத்தல்",
    translation: "Curbing of Desire",
    transliteration: "Avaavaruththal",
    id: 37,
    start: 361,
    end: 370,
    paalId: 1,
    iyalId: 3,
  },
  {
    name: "ஊழ்",
    translation: "Fate",
    transliteration: "Oozh",
    id: 38,
    start: 371,
    end: 380,
    paalId: 1,
    iyalId: 4,
  },
  {
    name: "இறைமாட்சி",
    translation: "The Greatness of a King",
    transliteration: "Iraimaatchi",
    id: 39,
    start: 381,
    end: 390,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "கல்வி",
    translation: "Learning",
    transliteration: "Kalvi",
    id: 40,
    start: 391,
    end: 400,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "கல்லாமை",
    translation: "Ignorance",
    transliteration: "Kallaamai",
    id: 41,
    start: 401,
    end: 410,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "கேள்வி",
    translation: "Hearing",
    transliteration: "Kelvi",
    id: 42,
    start: 411,
    end: 420,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "அறிவுடைமை",
    translation: "The Possession of Knowledge",
    transliteration: "Arivutaimai",
    id: 43,
    start: 421,
    end: 430,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "குற்றங்கடிதல்",
    translation: "The Correction of Faults",
    transliteration: "Kutrangatidhal",
    id: 44,
    start: 431,
    end: 440,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "பெரியாரைத் துணைக்கோடல்",
    translation: "Seeking the Aid of Great Men",
    transliteration: "Periyaaraith Thunaikkotal",
    id: 45,
    start: 441,
    end: 450,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "சிற்றினம் சேராமை",
    translation: "Avoiding mean Associations",
    transliteration: "Sitrinanjeraamai",
    id: 46,
    start: 451,
    end: 460,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "தெரிந்து செயல்வகை",
    translation: "Acting after due Consideration",
    transliteration: "Therindhuseyalvakai",
    id: 47,
    start: 461,
    end: 470,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "வலியறிதல்",
    translation: "The Knowledge of Power",
    transliteration: "Valiyaridhal",
    id: 48,
    start: 471,
    end: 480,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "காலமறிதல்",
    translation: "Knowing the fitting Time",
    transliteration: "Kaalamaridhal",
    id: 49,
    start: 481,
    end: 490,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "இடனறிதல்",
    translation: "Knowing the Place",
    transliteration: "Itanaridhal",
    id: 50,
    start: 491,
    end: 500,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "தெரிந்து தெளிதல்",
    translation: "Selection and Confidence",
    transliteration: "Therindhudhelidhal",
    id: 51,
    start: 501,
    end: 510,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "தெரிந்து வினையாடல்",
    translation: "Selection and Employment",
    transliteration: "Therindhuvinaiyaatal",
    id: 52,
    start: 511,
    end: 520,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "சுற்றந் தழால்",
    translation: "Cherishing Kinsmen",
    transliteration: "Sutrandhazhaal",
    id: 53,
    start: 521,
    end: 530,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "பொச்சாவாமை",
    translation: "Unforgetfulness",
    transliteration: "Pochchaavaamai",
    id: 54,
    start: 531,
    end: 540,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "செங்கோன்மை",
    translation: "The Right Sceptre",
    transliteration: "Sengonmai",
    id: 55,
    start: 541,
    end: 550,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "கொடுங்கோன்மை",
    translation: "The Cruel Sceptre",
    transliteration: "Kotungonmai",
    id: 56,
    start: 551,
    end: 560,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "வெருவந்த செய்யாமை",
    translation: "Absence of Terrorism",
    transliteration: "Veruvandhaseyyaamai",
    id: 57,
    start: 561,
    end: 570,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "கண்ணோட்டம்",
    translation: "Benignity",
    transliteration: "Kannottam",
    id: 58,
    start: 571,
    end: 580,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "ஒற்றாடல்",
    translation: "Detectives",
    transliteration: "Otraatal",
    id: 59,
    start: 581,
    end: 590,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "ஊக்கம் உடைமை",
    translation: "Energy",
    transliteration: "Ookkamutaimai",
    id: 60,
    start: 591,
    end: 600,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "மடி இன்மை",
    translation: "Unsluggishness",
    transliteration: "Matiyinmai",
    id: 61,
    start: 601,
    end: 610,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "ஆள்வினை உடைமை",
    translation: "Manly Effort",
    transliteration: "Aalvinaiyutaimai",
    id: 62,
    start: 611,
    end: 620,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "இடுக்கண் அழியாமை",
    translation: "Hopefulness in Trouble",
    transliteration: "Itukkan Azhiyaamai",
    id: 63,
    start: 621,
    end: 630,
    paalId: 2,
    iyalId: 5,
  },
  {
    name: "அமைச்சு",
    translation: "The Office of Minister of state",
    transliteration: "Amaichchu",
    id: 64,
    start: 631,
    end: 640,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "சொல்வன்மை",
    translation: "Power of Speech",
    transliteration: "Solvanmai",
    id: 65,
    start: 641,
    end: 650,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "வினைத் தூய்மை",
    translation: "Purity in Action",
    transliteration: "Vinaiththooimai",
    id: 66,
    start: 651,
    end: 660,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "வினைத்திட்பம்",
    translation: "Power in Action",
    transliteration: "Vinaiththitpam",
    id: 67,
    start: 661,
    end: 670,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "வினை செயல்வகை",
    translation: "Modes of Action",
    transliteration: "Vinaiseyalvakai",
    id: 68,
    start: 671,
    end: 680,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "தூது",
    translation: "The Envoy",
    transliteration: "Thoodhu",
    id: 69,
    start: 681,
    end: 690,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "மன்னரைச் சேர்ந்து ஒழுகல்",
    translation: "Conduct in the Presence of the King",
    transliteration: "Mannaraich Cherndhozhudhal",
    id: 70,
    start: 691,
    end: 700,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "குறிப்பறிதல்",
    translation: "The Knowledge of Indications",
    transliteration: "Kuripparidhal",
    id: 71,
    start: 701,
    end: 710,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "அவை அறிதல்",
    translation: "The Knowledge of the Council Chamber",
    transliteration: "Avaiyaridhal",
    id: 72,
    start: 711,
    end: 720,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "அவை அஞ்சாமை",
    translation: "Not to dread the Council",
    transliteration: "Avaiyanjaamai",
    id: 73,
    start: 721,
    end: 730,
    paalId: 2,
    iyalId: 6,
  },
  {
    name: "நாடு",
    translation: "The Land",
    transliteration: "Naatu",
    id: 74,
    start: 731,
    end: 740,
    paalId: 2,
    iyalId: 7,
  },
  {
    name: "அரண்",
    translation: "The Fortification",
    transliteration: "Aran",
    id: 75,
    start: 741,
    end: 750,
    paalId: 2,
    iyalId: 7,
  },
  {
    name: "பொருள் செயல்வகை",
    translation: "Way of Accumulating Wealth",
    transliteration: "Porulseyalvakai",
    id: 76,
    start: 751,
    end: 760,
    paalId: 2,
    iyalId: 8,
  },
  {
    name: "படை மாட்சி",
    translation: "The Excellence of an Army",
    transliteration: "Pataimaatchi",
    id: 77,
    start: 761,
    end: 770,
    paalId: 2,
    iyalId: 9,
  },
  {
    name: "படைச் செருக்கு",
    translation: "Military Spirit",
    transliteration: "Pataichcherukku",
    id: 78,
    start: 771,
    end: 780,
    paalId: 2,
    iyalId: 9,
  },
  {
    name: "நட்பு",
    translation: "Friendship",
    transliteration: "Natpu",
    id: 79,
    start: 781,
    end: 790,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "நட்பாராய்தல்",
    translation: "Investigation in forming Friendships",
    transliteration: "Natpaaraaidhal",
    id: 80,
    start: 791,
    end: 800,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பழைமை",
    translation: "Familiarity",
    transliteration: "Pazhaimai",
    id: 81,
    start: 801,
    end: 810,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "தீ நட்பு",
    translation: "Evil Friendship",
    transliteration: "Thee Natpu",
    id: 82,
    start: 811,
    end: 820,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "கூடா நட்பு",
    translation: "Unreal Friendship",
    transliteration: "Kootaanatpu",
    id: 83,
    start: 821,
    end: 830,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பேதைமை",
    translation: "Folly",
    transliteration: "Pedhaimai",
    id: 84,
    start: 831,
    end: 840,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "புல்லறிவாண்மை",
    translation: "Ignorance",
    transliteration: "Pullarivaanmai",
    id: 85,
    start: 841,
    end: 850,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "இகல்",
    translation: "Hostility",
    transliteration: "Ikal",
    id: 86,
    start: 851,
    end: 860,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பகை மாட்சி",
    translation: "The Might of Hatred",
    transliteration: "Pakaimaatchi",
    id: 87,
    start: 861,
    end: 870,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பகைத்திறம் தெரிதல்",
    translation: "Knowing the Quality of Hate",
    transliteration: "Pakaiththirandheridhal",
    id: 88,
    start: 871,
    end: 880,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "உட்பகை",
    translation: "Enmity within",
    transliteration: "Utpakai",
    id: 89,
    start: 881,
    end: 890,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பெரியாரைப் பிழையாமை",
    translation: "Not Offending the Great",
    transliteration: "Periyaaraip Pizhaiyaamai",
    id: 90,
    start: 891,
    end: 900,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "பெண்வழிச் சேறல்",
    translation: "Being led by Women",
    transliteration: "Penvazhichcheral",
    id: 91,
    start: 901,
    end: 910,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "வரைவின் மகளிர்",
    translation: "Wanton Women",
    transliteration: "Varaivinmakalir",
    id: 92,
    start: 911,
    end: 920,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "கள்ளுண்ணாமை",
    translation: "Not Drinking Palm-Wine",
    transliteration: "Kallunnaamai",
    id: 93,
    start: 921,
    end: 930,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "சூது",
    translation: "Gambling",
    transliteration: "Soodhu",
    id: 94,
    start: 931,
    end: 940,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "மருந்து",
    translation: "Medicine",
    transliteration: "Marundhu",
    id: 95,
    start: 941,
    end: 950,
    paalId: 2,
    iyalId: 10,
  },
  {
    name: "குடிமை",
    translation: "Nobility",
    transliteration: "Kutimai",
    id: 96,
    start: 951,
    end: 960,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "மானம்",
    translation: "Honour",
    transliteration: "Maanam",
    id: 97,
    start: 961,
    end: 970,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "பெருமை",
    translation: "Greatness",
    transliteration: "Perumai",
    id: 98,
    start: 971,
    end: 980,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "சான்றாண்மை",
    translation: "Perfectness",
    transliteration: "Saandraanmai",
    id: 99,
    start: 981,
    end: 990,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "பண்புடைமை",
    translation: "Courtesy",
    transliteration: "Panputaimai",
    id: 100,
    start: 991,
    end: 1000,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "நன்றியில் செல்வம்",
    translation: "Wealth without Benefaction",
    transliteration: "Nandriyilselvam",
    id: 101,
    start: 1001,
    end: 1010,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "நாணுடைமை",
    translation: "Shame",
    transliteration: "Naanutaimai",
    id: 102,
    start: 1011,
    end: 1020,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "குடிசெயல் வகை",
    translation: "The Way of Maintaining the Family",
    transliteration: "Kutiseyalvakai",
    id: 103,
    start: 1021,
    end: 1030,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "உழவு",
    translation: "Farming",
    transliteration: "Uzhavu",
    id: 104,
    start: 1031,
    end: 1040,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "நல்குரவு",
    translation: "Poverty",
    transliteration: "Nalkuravu",
    id: 105,
    start: 1041,
    end: 1050,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "இரவு",
    translation: "Mendicancy",
    transliteration: "Iravu",
    id: 106,
    start: 1051,
    end: 1060,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "இரவச்சம்",
    translation: "The Dread of Mendicancy",
    transliteration: "Iravachcham",
    id: 107,
    start: 1061,
    end: 1070,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "கயமை",
    translation: "Baseness",
    transliteration: "Kayamai",
    id: 108,
    start: 1071,
    end: 1080,
    paalId: 2,
    iyalId: 11,
  },
  {
    name: "தகை அணங்குறுத்தல்",
    translation: "The Pre-marital love",
    transliteration: "Thakaiyananguruththal",
    id: 109,
    start: 1081,
    end: 1090,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "குறிப்பறிதல்",
    translation: "Recognition of the Signs ",
    transliteration: "Kuripparidhal",
    id: 110,
    start: 1091,
    end: 1100,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "புணர்ச்சி மகிழ்தல்",
    translation: "Rejoicing in the Embrace",
    transliteration: "Punarchchimakizhdhal",
    id: 111,
    start: 1101,
    end: 1110,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "நலம் புனைந்து உரைத்தல்",
    translation: "The Praise of her Beauty",
    transliteration: "Nalampunaindhuraiththal",
    id: 112,
    start: 1111,
    end: 1120,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "காதற் சிறப்புரைத்தல்",
    translation: 'Declaration of Love"s special Excellence',
    transliteration: "Kaadharsirappuraiththal",
    id: 113,
    start: 1121,
    end: 1130,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "நாணுத் துறவுரைத்தல்",
    translation: "The Abandonment of Reserve",
    transliteration: "Naanuththuravuraiththal",
    id: 114,
    start: 1131,
    end: 1140,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "அலர் அறிவுறுத்தல்",
    translation: "The Announcement of the Rumour",
    transliteration: "Alararivuruththal",
    id: 115,
    start: 1141,
    end: 1150,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "பிரிவு ஆற்றாமை",
    translation: "Separation unendurable",
    transliteration: "Pirivaatraamai",
    id: 116,
    start: 1151,
    end: 1160,
    paalId: 3,
    iyalId: 12,
  },
  {
    name: "படர்மெலிந் திரங்கல்",
    translation: "Complainings",
    transliteration: "Patarmelindhirangal",
    id: 117,
    start: 1161,
    end: 1170,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "கண் விதுப்பழிதல்",
    translation: "Eyes consumed with Grief",
    transliteration: "Kanvidhuppazhidhal",
    id: 118,
    start: 1171,
    end: 1180,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "பசப்புறு பருவரல்",
    translation: "The Pallid Hue",
    transliteration: "Pasapparuparuvaral",
    id: 119,
    start: 1181,
    end: 1190,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "தனிப்படர் மிகுதி",
    translation: "The Solitary Anguish",
    transliteration: "Thanippatarmikudhi",
    id: 120,
    start: 1191,
    end: 1200,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "நினைந்தவர் புலம்பல்",
    translation: "Sad Memories",
    transliteration: "Ninaindhavarpulampal",
    id: 121,
    start: 1201,
    end: 1210,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "கனவுநிலை உரைத்தல்",
    translation: "The Visions of the Night",
    transliteration: "Kanavunilaiyuraiththal",
    id: 122,
    start: 1211,
    end: 1220,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "பொழுதுகண்டு இரங்கல்",
    translation: "Lamentations at Eventide",
    transliteration: "Pozhudhukantirangal",
    id: 123,
    start: 1221,
    end: 1230,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "உறுப்புநலன் அழிதல்",
    translation: "Wasting Away",
    transliteration: "Uruppunalanazhidhal",
    id: 124,
    start: 1231,
    end: 1240,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "நெஞ்சொடு கிளத்தல்",
    translation: "Soliloquy",
    transliteration: "Nenjotukilaththal",
    id: 125,
    start: 1241,
    end: 1250,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "நிறையழிதல்",
    translation: "Reserve Overcome",
    transliteration: "Niraiyazhidhal",
    id: 126,
    start: 1251,
    end: 1260,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "அவர்வயின் விதும்பல்",
    translation: "Mutual Desire",
    transliteration: "Avarvayinvidhumpal",
    id: 127,
    start: 1261,
    end: 1270,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "குறிப்பறிவுறுத்தல்",
    translation: "The Reading of the Signs",
    transliteration: "Kuripparivuruththal",
    id: 128,
    start: 1271,
    end: 1280,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "புணர்ச்சி விதும்பல்",
    translation: "Desire for Reunion",
    transliteration: "Punarchchividhumpal",
    id: 129,
    start: 1281,
    end: 1290,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "நெஞ்சொடு புலத்தல்",
    translation: "Expostulation with Oneself",
    transliteration: "Nenjotupulaththal",
    id: 130,
    start: 1291,
    end: 1300,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "புலவி",
    translation: "Pouting",
    transliteration: "Pulavi",
    id: 131,
    start: 1301,
    end: 1310,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "புலவி நுணுக்கம்",
    translation: "Feigned Anger",
    transliteration: "Pulavi Nunukkam",
    id: 132,
    start: 1311,
    end: 1320,
    paalId: 3,
    iyalId: 13,
  },
  {
    name: "ஊடலுவகை",
    translation: "The Pleasures of Temporary Variance",
    transliteration: "Ootaluvakai",
    id: 133,
    start: 1321,
    end: 1330,
    paalId: 3,
    iyalId: 13,
  },
];
