module.exports = [
  {
    name: "பாயிரவியல்",
    transliteration: "Paayiraviyal",
    translation: "Prologue",
    id: 1,
    paalId: 1,
  },
  {
    name: "இல்லறவியல்",
    transliteration: "Illaraviyal",
    translation: "Domestic Virtue",
    id: 2,
    paalId: 1,
  },
  {
    name: "துறவறவியல்",
    transliteration: "Thuravaraviyal",
    translation: "Ascetic Virtue",
    id: 3,
    paalId: 1,
  },
  {
    name: "ஊழியல்",
    transliteration: "Oozhiyal",
    translation: "Fate",
    id: 4,
    paalId: 1,
  },
  {
    name: "அரசியல்",
    transliteration: "Arasiyal",
    translation: "Royalty",
    id: 5,
    paalId: 2,
  },
  {
    name: "அமைச்சியல்",
    transliteration: "Amaichiyal",
    translation: "Minister of State",
    id: 6,
    paalId: 2,
  },
  {
    name: "அரணியல்",
    transliteration: "Araniyal",
    translation: "The Essentials of a State",
    id: 7,
    paalId: 2,
  },
  {
    name: "கூழியல்",
    transliteration: "Koozhiyal",
    translation: "Way of Making Wealth",
    id: 8,
    paalId: 2,
  },
  {
    name: "படையில்",
    transliteration: "Padaiyil",
    translation: "The Excellence of an Army",
    id: 9,
    paalId: 2,
  },
  {
    name: "நட்பியல்",
    transliteration: "Natpiyal",
    translation: "Friendship",
    id: 10,
    paalId: 2,
  },
  {
    name: "குடியியல்",
    transliteration: "Kudiyiyal",
    translation: "Miscellaneous",
    id: 11,
    paalId: 2,
  },
  {
    name: "களவியல்",
    transliteration: "Kalaviyal",
    translation: "The Pre-marital love",
    id: 12,
    paalId: 3,
  },
  {
    name: "கற்பியல்",
    transliteration: "Karpiyal",
    translation: "The Post-marital love",
    id: 13,
    paalId: 3,
  },
];
